spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  eureka:
    instance:
      prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

#activity-service.url=${ACTIVITY_SERVICE_URL:http://localhost:8081}
# user-management-service.url=${USER_MANAGEMENT_SERVICE_URL:http://localhost:8082}
